version: "3.8"
name: wa-connector

services:
  wa-connector:
    build:
      context: .  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile 
    container_name: wa-connector
    ports:
      - "5007:5007"
    env_file:
      - .env # Load environment variables from the .env file

